### ISSUE TITLE
vector_project(camera)

### ISSUE THREAD

**Issue by Korijn** [pygfx/pylinalg#11]
Project a vector onto a view plane

**Comment by FirefoxMetzger** [comment]
Hm. @Korijn Could you add some more detail on what is needed here? In particular, which type of camera are we interested in and what would the signature of this function look like?

My naive guess would be that the task is to write a function that can take any point inside a perspective camera's viewing frustum and map it onto the camera's viewing plane. Is that correct?

**Comment by Korijn** [comment]
See https://github.com/pygfx/pygfx/blob/6642d1cd907f068cc7e7ca4cc4e42c4763e76c81/pygfx/linalg/vector3.py#L185

Essentially you map a point from world space to screen space. The camera type doesn't really matter, any projection matrix is fine.

**Comment by FirefoxMetzger** [comment]
In https://github.com/pygfx/pylinalg/pull/22#discussion_r1043455656 we decided that we don't need `vector_project(camera)` and that we will instead use `vector_apply_matrix`.

Shall we close?
