### ISSUE TITLE
vector_unproject

### ISSUE THREAD

**Issue by Korijn** [pygfx/pylinalg#12]
Unproject a vector from a view plane

**Comment by FirefoxMetzger** [comment]
This one is interesting, since going from 2D to 3D is not unique. Would unproject return a line or would we specify a distance from the camera, too, so we can actually find a unique 3D point?

**Comment by Korijn** [comment]
See https://github.com/pygfx/pygfx/blob/6642d1cd907f068cc7e7ca4cc4e42c4763e76c81/pygfx/linalg/vector3.py#L189

**Comment by Korijn** [comment]
Yes, see #6 :+1:
