### ISSUE TITLE
vector_translation_from_transform

### ISSUE THREAD

**Issue by Korijn** [pygfx/pylinalg#17]
Grab the translation component from a transform matrix

**Comment by FirefoxMetzger** [comment]
It looks like we didn't write a stub for this in #22 . Would you like me to create one, or did we decide to skip this function? (I can't remember.)

**Comment by FirefoxMetzger** [comment]
Nvm, I found the stub. It's called `vector_from_matrix_position` (I was looking for the wrong name).
