### ISSUE TITLE
remove cap on poetry version in CI

### ISSUE THREAD

**Issue by FirefoxMetzger** [pygfx/pylinalg#27]
Poetry is currently using v1.3.1 but our CI limits this to `poetry<1.2`. Is there a particular reason for this, or can we bump this cap to `poetry<2` i.e. the next version-major?

**Edit:** Considering poetry*s [official CI recommendations](https://python-poetry.org/docs/#ci-recommendations), we could also pin the version explicitly, but I would still like to move to v1.3 :)

**Comment by Korijn** [comment]
I'm fine with upgrading. For a long time 1.2's big internal rewrite brought a lot of regressions with it that broke our projects. We pinned it across the board for a while.
