### ISSUE TITLE
Document coordinate frame axes conventions

### ISSUE THREAD

**Issue by Korijn** [pygfx/pylinalg#31]
* Local space, view space, NDC space, wgpu space:
  * positive z is viewing direction
  * positive x is right
  * positive y is up

What is up in world space, depends on the application. This is why the camera and some routines in pylinalg have a configurable up vector.

**Comment by FirefoxMetzger** [comment]
I think this would be a good candidate for a gallery example. It's a bit verbose to describe, but becomes clear immediately with a picture (or two). We have the `pygfx.AxisHelper` (which I just documented) that would come in quite handy for this purpose.
