### ISSUE TITLE
Check that we are consistent with our coordinate frame conventions.

### ISSUE THREAD

**Issue by FirefoxMetzger** [pygfx/pylinalg#44]
Looking at the recent discussion in https://github.com/pygfx/pygfx/issues/460 and the decision that negative Z means "forward", there are a couple of places where we use a different definition. From the top of my head, these are at least

- [ ] `vector_spherical_to_euclidean`
- [ ] `vector_euclidean_to_spherical`
- [ ] `matrix_make_look_at`

All of these use the definition that "forward" is positive Z, so they will need updating to match our chosen definition. There might be others, so we should probably keep an eye out for these.

---

There is a second convention that we didn't specify explicitly yet: spherical coordinates. Currently, we are using the definition that spherical coordinates are given as `(radius, theta, phi)` with `radius in [-inf, inf]`, `theta in [0, pi]`, and `phi in [0, 2pi]`. Theta is measured from positive Z and phi is measured from positive Y. We want to change this to have theta measured from negative Z, but if we update this it's worthwhile to ask if it is otherwise the definition we want to use going forward, or if we want to change it further. 

An alternative "natural" choice would be to allow `theta in [-pi, pi]` measured from Z and `phi in [-pi/2, pi/2]` measured from the XZ plane. This lends itself to head/camera movements, as the numerical values would now represent the relative "pan" and "tilt" angles for a (relative) camera movement. This definition would be more "human friendly" at the expense of making the internal math a little less by the book.

Another common way to define spherical coordinates is to measure `phi` from the XZ plane instead of from Y (as in the previous option). This is common in astronomy when tracking stars in the sky because it gives you the observer's azimuth and altitude angles directly. (It's also useful when building aimbots for world of tanks, because it tells you how to position your cannon to aim for a target, lol)

**Comment by Korijn** [comment]
As far as I know the current implementations are consistent with those in three.js.

**Comment by almarklein** [comment]
> An alternative "natural" choice would be to allow theta in [-pi, pi] measured from Z and phi in [-pi/2, pi/2] measured from the XZ plane.

I'd say we go with the original (more mathy) definition. In places where we have a azimuth/elevation situation where the symmetric ranges feel more natural, we can just do some addition/subtraction.

> `radius in [-inf, inf]`

Would that be `[0, inf]`?

**Comment by FirefoxMetzger** [comment]
Oh yes, good catch. A negative radius doesn't make much sense.
