### ISSUE TITLE
Duplicate method `vector_apply_quaternion_rotation` and `quaternion_rotate`?

### ISSUE THREAD

**Issue by FirefoxMetzger** [pygfx/pylinalg#52]
I think we have two functions (see title) that do the same thing. If this is true, which one shall we keep?

**Comment by Korijn** [comment]
Can you make the decision?

**Comment by FirefoxMetzger** [comment]
@Korijn Of course. I would keep `vector_apply_quaternion_rotation` (perhaps drop the `_rotation` bit). It follows the logic of `vector_apply_matrix` in that you take a vector, operate on it, and output a vector.

**Comment by Korijn** [comment]
Sounds good to me.
