### ISSUE TITLE
Add `vector_euler_angles_from_quaternion`

### ISSUE THREAD

**Issue by FirefoxMetzger** [pygfx/pylinalg#68]
We can already go from Euler angles to quaternions, and it would also be good to be able to do the reverse/inverse. 

We could use this, for example, in pygfx to implement getters and setters for rotations on the transform classes, e.g. `obj.world.euler_rotation = (alpha, beta, gamma)` or `obj.world.euler_x = 42`.

**Comment by Korijn** [comment]
For me, realizing this idea (including the euler setters in pygfx) and #67 and #70 together are the new priorities @FirefoxMetzger 

How much time do we have left for you this year? :)
